---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
#         - name: presync-job-1
#           image: alpine:latest
#           command: ["ls", "-l"]
        - name: presync-job-2
          image: ubuntu
          command: 
            - /bin/bash
            - -c
            - |
              apt update -y
              apt upgrade -y
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: resource-hook-curl-pre
  annotations:
    argocd.argoproj.io/hook: PostSync    
spec:
  template:
    spec:
      containers:
        - name: resource-hook-curl-pre
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
  backoffLimit: 2

