apiVersion: batch/v1
kind: Job
metadata:
  generateName: upgrade-sql-schema
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      containers:
        - name: curl-localhost
          image: curlimages/curl
          command:
            - "curl"
            - "-d"
            - "'{\"message\":\"this is my first webhook\"}'"
            - "-H"
            - "\"Content-Type: application/json\""
            - "-X"
            - "POST"
             - "http://localhost:12000/example"
      restartPolicy: Never
  backoffLimit: 2
