apiVersion: batch/v1
kind: Job
metadata:
  generateName: Post-Sync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: Post-Sync-Job
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never 
